/* CARGA DATOS EN LA TABLA city */
SELECT * 
FROM city;

INSERT INTO city(ID, STATE_ID, NAME)
VALUES ('1', '1', 'CITY 1');

INSERT INTO city(ID, STATE_ID, NAME)
VALUES ('2', '2', 'CITY 2');

INSERT INTO city(ID, STATE_ID, NAME)
VALUES ('3', '3', 'CITY 3');

INSERT INTO city(ID, STATE_ID, NAME)
VALUES ('4', '4', 'CITY 4');

INSERT INTO city(ID, STATE_ID, NAME)
VALUES ('5', '5', 'CITY 5');