/* CARGA DATOS EN LA TABLA place */
SELECT * 
FROM place;

INSERT INTO place(ID, USER_ID, NAME, CITY_ID, DESCRIPTION, NUMBER_ROOMS, NUMBER_BATHROOMS, MAX_GUEST, PRICE_BY_NIGHT, LATITUDE, LONGITUDE)
VALUES ('1', '1', 'CITY 1', '1', 'DESCRIPTION 1', 0, 0, 0, 0, 0, 0);

INSERT INTO place(ID, USER_ID, NAME, CITY_ID, DESCRIPTION, NUMBER_ROOMS, NUMBER_BATHROOMS, MAX_GUEST, PRICE_BY_NIGHT, LATITUDE, LONGITUDE)
VALUES ('2', '2', 'CITY 2', '2', 'DESCRIPTION 2', 0, 0, 0, 0, 0, 0);

INSERT INTO place(ID, USER_ID, NAME, CITY_ID, DESCRIPTION, NUMBER_ROOMS, NUMBER_BATHROOMS, MAX_GUEST, PRICE_BY_NIGHT, LATITUDE, LONGITUDE)
VALUES ('3', '3', 'CITY 3', '3', 'DESCRIPTION 3', 0, 0, 0, 0, 0, 0);

INSERT INTO place(ID, USER_ID, NAME, CITY_ID, DESCRIPTION, NUMBER_ROOMS, NUMBER_BATHROOMS, MAX_GUEST, PRICE_BY_NIGHT, LATITUDE, LONGITUDE)
VALUES ('4', '4', 'CITY 4', '4', 'DESCRIPTION 4', 0, 0, 0, 0, 0, 0);

INSERT INTO place(ID, USER_ID, NAME, CITY_ID, DESCRIPTION, NUMBER_ROOMS, NUMBER_BATHROOMS, MAX_GUEST, PRICE_BY_NIGHT, LATITUDE, LONGITUDE)
VALUES ('5', '5', 'CITY 5', '5', 'DESCRIPTION 5', 0, 0, 0, 0, 0, 0);