/* CARGA DATOS EN LA TABLA USUARIOS */

SELECT * 
FROM USUARIO;

INSERT INTO USUARIO(ID, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME)
VALUES ('1', 'andres@outlook.com', '123456789', 'ANDRES', 'GIRALDO');

INSERT INTO usuario(ID, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME)
VALUES ('2', 'andres@outlook.com', '123456789', 'JUAN', 'OCAMPO');

INSERT INTO usuario(ID, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME)
VALUES ('3', 'andres@outlook.com', '123456789', 'CARLOS', 'TIJO');

INSERT INTO usuario(ID, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME)
VALUES ('4', 'andres@outlook.com', '123456789', 'ALEX', 'GALLEGO');

INSERT INTO usuario(ID, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME)
VALUES ('5', 'andres@outlook.com', '123456789', 'MARTIN', 'TOVAR');